name: Delete terraform resources
on:
    workflow_dispatch:
    schedule: 
            - cron: '0 0 * * *'

jobs:
    destroy_resources:
        runs-on: ubuntu-latest
        env:
            AWS_REGION: us-east-1
            TF_VERSION: 1.5.0
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: set up aws
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            
            - name: set up terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform-version: ${{ env.TF_VERSION }}
            
            - name: terraform init
              run: terraform init
              
            - name: 'Terraform destroy'
              run: terraform plan -destroy -out=tfplan-destroy 

            - name: 'Terraform Apply Destroy'
              run: terraform apply -auto-approve tfplan-destroy


        
